config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("bookings.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs")
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path('create/', views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    # path("login/google", views.google_login, name="google-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="Profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

templates/partials/footer.html
{% load i18n %}
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-400">
    &copy;  {% trans "BookMyPG" %}
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute top-0 mx-auto left-0 right-0 z-10 flex justify-center">
        {% for message in messages %}
        <li class="font-medium top-0 bg-gray-600 rounded-full text-white py-4 px-6 {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated %}
        <li class="ml-5 border-b-2 border-white hover:border-gray-600 h-full flex items-center">
            <a class="py-10 px-3" href="{% url 'users:switch-hosting' %}">
                {% if request.session.is_hosting %}
                    stop hosting
                {% else %}
                    start hosting
                {% endif %}
            </a>
        </li>
        {% if request.session.is_hosting %}
            <li class="ml-5 border-b-2 border-white hover:border-gray-600 h-full flex items-center"><a class="py-10 px-3" href="{% url 'rooms:create' %}">Create Room</a></li>
        {% endif %}

        <li class="ml-5 border-b-2 border-white hover:border-gray-600 h-full flex items-center"><a class="py-10 px-3" href="{{user.get_absolute_url}}">Profile</a></li>
        <li class="ml-5 border-b-2 border-white hover:border-gray-600 h-full flex items-center"><a class="py-10 px-3" href="{% url 'lists:see-favs' %}">Fav({{user.list.rooms.count}}) </a></li>
        <li class="ml-5 border-b-2 border-white hover:border-gray-600 h-full flex items-center"><a class="py-10 px-3" href="{% url "users:logout" %}">Log Out</a></li>
    {% else %}
        <li class="ml-5 border-b-2 border-white hover:border-gray-600 h-full flex items-center"><a class="py-10 px-3" href="{% url "users:login" %}">Login</a></li>
        <li class="ml-5 border-b-2 border-white hover:border-gray-600 h-full flex items-center"><a class="py-10 px-3" href="{% url "users:signup" %}">SignUp</a></li>
    {% endif %}
</ul>

    

templates/partials/room_card.html
<div class="w-1/4 mb-10 px-2">
    <a href="{% url 'rooms:detail' room.pk %}">
    <div class="w-full h-64 bg-cover bg-center rounded-lg mb-4" style="background-image: url({{room.first_photo}});">
    </div>

    <div class="flex justify-between mb-2">
        <div>

            {% if room.owner.superhost %}
            <i class="fa-solid fa-circle-check"></i>
            <span class="mr-px uppercase font-medium text-green-600 border border-green-700 rounded py-px px-1">verified</span>
            {% endif %}

            <span class="text-sm text-gray-600">{{room.city}}, {{room.country.name}}</span>
        </div>
        <span class="text-sm items-center">
             
            <i class="fa fa-solid fa-star text-red-600 text-xs mr-1"></i>{{room.total_rating}}
        </span>
    </div>

    <span class="text-black font-medium">
        
            {{room.name}} / Rs.{{room.price}}
        
    </span>
    
    </a>
    
</div>

templates/partials/social_login.html
<div class="flex flex-col w-full">

    <a href="{% url 'users:github-login' %}" class="w-full border-2 font-bold text-gray-500 border-gray-700 text-center rounded-sm p-3">
        <i class="fab fa-github mr-2 fa-lg"></i> continue with github
    </a>
    <br>
    <a href="/accounts/google/login" class="w-full border font-bold bg-red-500 text-white border-red-800 text-center rounded-sm p-3">
        <i class="fab fa-google mr-2 fa-lg"></i> continue with gmail
    </a>

</div>
<div class="flex items-center w-full my-3">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 mx-4 font-bold">or</span>
    <div class="h-px w-full bg-gray-400"></div>

</div>

templates/partials/user_avatar.html
{% if user.avatar %}
<div class="{{h_and_w|default:'h-20 w-20'}} rounded-full bg-cover" style="background-image: url({{user.avatar.url}});">
{% else %}
    <div class="{{h_and_w|default:'h-20 w-20'}} bg-gray-700 rounded-full text-white flex justify-center items-center">
        <span class="{{text|default:'text-3xl'}}">{{user.first_name|first}}</span>
    </div>
{% endif %}