bookings/urls.py
from django.urls import path
from . import views

app_name = "bookings"

urlpatterns = [
    path("create/<int:room>/<int:year>-<int:month>-<int:day>/", views.create, name="create"),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("bookings.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>/", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs")
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path('create/', views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/", views.delete_photo, name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/", views.EditPhotoView.as_view(), name="edit-photo"),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    # path("login/google", views.google_login, name="google-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="Profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

rooms/forms.py
from typing import Any
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="anywhere")
    country = CountryField(default="IN").formfield()
    room_type = forms.ModelChoiceField(
        required=False,
        empty_label="any kind",
        queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    superhost = forms.BooleanField(required=False)
    instant_book = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )   
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )


class CreatePhotoForm(forms.ModelForm):

    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):

    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "persons",
            "beds",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "house_rules",
            "facilities",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
# from math import ceil
# from django.urls import reverse
from django.forms.forms import BaseForm
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
# from django.http import Http404
from django.core.paginator import Paginator, EmptyPage
from django.urls import reverse, reverse_lazy

from . import models, forms
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django_countries import countries
from users import mixins as user_mixins
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

# Create your views here.

# def all_rooms(request):
#     page = request.GET.get("page", 1)
#     if page == "":
#       page = 1
#     else:
#       page = int(page)
#     page_size = 10
#     limit = page_size * page
#     offset = limit - page_size
#     all_rooms = models.Room.objects.all()[offset:limit]
#     page_count = ceil(models.Room.objects.count() / page_size)
#     return render(request, "rooms/home.html", context={
#       "rooms": all_rooms,
#       "page": page,
#       "page_count": page_count,
#       "page_range": range(1, page_count),
#     })


# better way than above one by using django paginator 

# def all_rooms(request):
#     page = request.GET.get("page", 1)
#     room_list = models.Room.objects.all()
#     paginator = Paginator(room_list, 10, orphans=5)
#     try:
#         rooms = paginator.page(int(page))
#         return render(
#             request,
#             "rooms/home.html",
#             {
#                 "page": rooms,
#             },
#         )
#     except EmptyPage:
#         rooms = paginator.page(1)
#         return redirect("/")


class HomeView(ListView):

    """ HomeView definition """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


# def room_detail(request, pk):
#     try:
#         room = models.Room.objects.get(pk=pk)
#         return render(request, "rooms/details.html", {
#             "room": room,
#         })
#     except models.Room.DoesNotExist:
#         raise Http404


class RoomDetail(DetailView):

    """ DetailView definition """

    model = models.Room


# def search(request):
#     city = request.GET.get("city", "anywhere")
#     city = str.capitalize(city)
#     country = request.GET.get("country", "IN")
#     room_type = int(request.GET.get("room_type", 3))
#     price = int(request.GET.get("price", 0))
#     person = int(request.GET.get("person", 0))
#     beds = int(request.GET.get("beds", 0))
#     baths = int(request.GET.get("baths", 0))
#     instant = request.GET.get("super_host", False)
#     super_host = request.GET.get("super_host", False)
#     s_amenities = request.GET.getlist("amenities")
#     f_facilities = request.GET.getlist("facilities")
    
#     form = {
#         "city": city,
#         "s_room_type": room_type,
#         "s_country": country,
#         "price": price,
#         "person": person,
#         "beds": beds,
#         "baths": baths,
#         "s_amenities": s_amenities,
#         "f_facilities": f_facilities,
#         "instant": instant,
#         "super_host": super_host,
#     }

#     room_types = models.RoomType.objects.all()
#     amenities = models.Amenity.objects.all()
#     facilities = models.Facility.objects.all()

#     choices = {
#         "countries": countries,
#         "room_types": room_types,
#         "amenities": amenities,
#         "facilities": facilities,
#     }

#     filter_args = {}

#     if city != "Anywhere":
#         filter_args["city__startswith"] = city

#     filter_args["country"] = country

#     if room_type != 0:
#         filter_args["room_type__pk"] = room_type

#     if price != 0:
#         filter_args["price__lte"] = price

#     if person != 0:
#         filter_args["person__gte"] = person

#     if beds != 0:
#         filter_args["beds__gte"] = beds

#     if baths != 0:
#         filter_args["baths__gte"] = baths

#     if instant is True:
#         filter_args["instant_book"] = True

#     if super_host is True:
#         filter_args["host__superhost"] = True

#     if len(s_amenities) > 0:
#         for s_amenity in s_amenities:
#             filter_args["amenities__pk"] = int(s_amenity)

#     if len(f_facilities) > 0:
#         for f_facility in f_facilities:
#             filter_args["facilities__pk"] = int(f_facility)

#     rooms = models.Room.objects.filter(**filter_args)

#     return render(request, "rooms/search.html", {
#         **form,
#         **choices,
#         "rooms": rooms,
#     })


class SearchView(View):

    def get(self, request):
        country = request.GET.get("country")

        if country:

            form = forms.SearchForm(request.GET)

            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                superhost = form.cleaned_data.get("superhost")
                instant_book = form.cleaned_data.get("instant_book")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                return render(request, "rooms/search.html", {
                    "form": form,
                    "rooms": rooms
                })

        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {
            "form": form,
        })


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "persons",
        "beds",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "house_rules",
        "facilities",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.owner.pk != self.request.user.pk:
            raise Http404()
        return room
    

class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.owner.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    # print(f"should delete {photo_pk} from {room_pk}")
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.owner.pk != user.pk:
            messages.error(request, "Can't delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "Photo Deleted")
        return redirect(reverse("rooms:photos", kwargs={'pk': room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"
    success_message = "Photo Updated"
    fields = (
        "caption",
    )

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={'pk': room_pk})


class AddPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin,FormView):

    # model = models.Photo
    template_name = "rooms/photo_create.html"
    # fields = (
    #     "caption",
    #     "file",
    # )
    form_class = forms.CreatePhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/room_create.html"
    form_class = forms.CreateRoomForm
    print("Hello1111")

    def form_valid(self, form):
        room = form.save()
        room.owner = self.request.user
        room.save()
        form.save_m2m() 

templates/rooms/room_create.html
{% extends "base.html" %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    
    <div class="container lg:border-yellow-500 lg:w-80 md:w-1/2 xl:w-1/4 my-10 mx-auto justify-center items-center flex flex-col border p-6 border-gray-400">

     

        <form method="POST" action="{% url 'rooms:create' %}" class="w-full" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <!-- <inpuat type="email" placeholder="Email" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id="">
            <input type="password" placeholder="Password" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id=""> -->
            <button class=" w-full border-2 text-center rounded-sm p-3 bg-yellow-500">Create</button>
        </form>

        
    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html"  %}
{% load is_booked on_favs %}
{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}


    <div class="-mt-5 conatainer max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-cover bg-center" style="background-image: url({{room.first_photo}});">
        </div>

        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div style="background-image: url({{photo.file.url}});" class="w-1/2 h-auto bg-cover bg-center border-gray-400 border"></div>
            {% endfor %}
        </div>
    </div>

    <div class="container font-semibold mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div>
                    <h4 class="text-3xl font-medium mb-px">
                        {{room.name}}
                    </h4>
                    <span class="text-gray-700 font-light">{{room.city}}</span>
                </div>
                <a href="{{room.owner.get_absolute_url}}" class="flex flex-col items-center">
                    <!-- {% include "partials/user_avatar.html" with user=room.owner %} -->
                    {{room.owner.first_name}}
                </a>
            </div>
            <div class="flex mb-5">
                {{room.room_type}}
                {{room.get_beds}}
            </div>
            <div class="border-t-2">
                <h4 class="font-medium text-lg mt-5 mb-5">House Rules</h4>
                {% for rule in room.house_rules.all %}
                    <li class="mb-2">{{rule}}</li>
                {% endfor %}
            </div>

            <div class="grid grid-cols-2 gap-4">
                
                <div>
                    <h4 class="font-medium text-lg mt-5 mb-5">Amenities</h4>
                    {% for amenity in room.amenities.all %}
                        <li>{{amenity}}</li>
                    {% endfor %}
                </div>
                <div>
                    <h4 class="font-medium text-lg mt-5 mb-5">Facilities</h4>
                    {% for facility in room.facilities.all %}
                        <li>{{facility}}</li>
                    {% endfor %}
                </div>
                
            </div>

            <div class="mt-10">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div class="mr-5">
                        <i class="fas fa-star text-green-600"></i>
                        <span class="font-bold text-xl">{{room.total_rating}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{room.reviews.count}} </span>
                        <span>review{{room.reviews.count|pluralize}}</span>
                    </div>
                </div>

                

                <div class="mt-10">
                    {% for review in room.reviews.all %}
                        <div class="border-t-2 mt-5">
                            <div class="mb-5 flex">
                                <div>
                                    <!-- {% include "partials/user_avatar.html" with user=review.user h_and_w='w-10 h-10' text='1' %} -->
                                </div>
                                <div class="flex flex-col ml-5">
                                    <span class="font-bold">{{review.user.first_name}}</span>
                                    <span class="text-sm text-gray-500">{{review.created}}</span>
                                </div>
                            </div>
                            <p>{{review.review}}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="w-1/3">
            <div class="flex">
                {% if user.is_authenticated %}
                    {% on_favs room as on_favs_boolean %}
                    {% if on_favs_boolean %}
                        <a href="{% url "lists:toggle-room" room.pk %}?action=remove" class="my-5 text-red-800" title="Remove from Favouriates">
                            <i class="fas fa-sharp fa-solid fa-heart-broken fa-3x">   </i>
                        </a>
                    {% else %}
                    
                        <a href="{% url "lists:toggle-room" room.pk %}?action=add" class="my-5 hover:text-yellow-400 text-red-800" title="Add to Favouriates">
                            <i class="fas fa-sharp fa-solid fa-heart fa-3x">   </i>
                        </a>
                    {% endif %}
                {% endif %}
                {% if room.owner == user %}
                    <a href="{% url 'rooms:edit' room.pk %}" class="text-center  py-3 rounded-lg font-light text-lg w-full h-1/4 mt-5 mx-4 text-white bg-red-500 block">Edit Room</a>
                {% endif %}

            </div>
            
 
                {% if not request.session.is_hosting %}
                    
                    {% for calendar in room.get_calendars %}
                        <div class="mb-20">
                            
                            
                            <span class="text-center font-bold text-lg block mb-8"> {{calendar.get_month}} / {{calendar.year}} </span>
                            <div class="mb-4 " style="display: grid; grid-template-columns: repeat(7, 1fr); grid-gap: 10px; justify-items: center;">
                                {% for day in calendar.day_names %}
                                    <span>{{day}}</span>
                                {% endfor %}
                            </div>
                            <div   style="
                            display: grid;
                            grid-template-columns: repeat(7, 1fr);
                            grid-gap: 10px;
                            justify-items: center;
                          ">
                                {% for day in calendar.get_days %}
                                    {% is_booked room day as is_booked_bool %}
                                        {% if day.number != 0 %}
                                        {% if day.past %}
                                            <span class="class rounded bg-gray-200 w-full text-center p-1 text-gray-400">{{day}}</span>
                                        {% elif is_booked_bool %}
                                            <span class="class rounded bg-gray-200 w-full text-center p-1 text-gray-400 line-through">{{day}}</span>
                                        {% else %}
                                            {% if user.is_authenticated %}
                                                <a href="{% url 'bookings:create' room.pk day.year day.month day.number %}" class="bg-gray-200 w-full text-center rounded text-yellow-700 p-1 hover:bg-yellow-300 hover:text-black cursor-pointer">{{day}}</a>
                                            {% else %}
                                                <a href="{% url 'users:login' %}" class="bg-gray-200 w-full text-center rounded text-yellow-700 p-1 hover:bg-yellow-300 hover:text-black cursor-pointer">{{day}}</a>
                                            {% endif %}
                                        {% endif %}
                                    {% else %}
                                        <span></span>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            
        </div>
        
    </div>

    <!-- <h1>{{room.name}}</h1>
    <h2> By <a href="{{room.owner.get_absolute_url}}">{{room.owner.username}}</a>
        {% if room.host.superhost %}
            (superhost)
        {% endif %}
    </h2>
    <h2>{{room.description}}</h2> <h3> Rs. {{room.price}}</h3>

    <h3>Amenities:
        {% for a in room.amenities.all %}
            <ul>
                <li>{{a}}</li>
            </ul>
        {% endfor %}
        
        <h3>Facilities:
            {% for a in room.facilities.all %}
                <ul>
                    <li>{{a}}</li>
                </ul>
            {% endfor %}
        </h3>

        <h3>House Rules:
            {% for a in room.house_rules.all %}
                <ul>
                    <li>{{a}}</li>
                </ul>
            {% endfor %}
        </h3>
        
    </h3> -->

{% endblock content %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    
    <div class="container lg:border-yellow-500 lg:w-80 md:w-1/2 xl:w-1/4 my-10 mx-auto justify-center items-center flex flex-col border p-6 border-gray-400">

     

        <form method="POST" action="{% url 'rooms:edit' room.pk %}" class="w-full" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <!-- <inpuat type="email" placeholder="Email" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id="">
            <input type="password" placeholder="Password" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id=""> -->
            <button class=" w-full border-2 text-center rounded-sm p-3 bg-yellow-500">Update</button>
        </form>

        
    </div>
{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    
    <div class="container lg:border-yellow-500 my-10 mx-auto justify-center flex flex-col">

        <div class="my-10 w-full">
            <a class="text-center ml-4 py-3 rounded-lg font-light text-lg text-white bg-red-500 block  w-1/6" href="{% url 'rooms:add-photo' room.pk %}">Upload Photos</a>
        </div>        

        {% for photo in room.photos.all %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32" alt="">
                    <span class="ml-5 text-xl">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="text-center ml-4 py-3 rounded-lg font-light text-lg w-full text-white bg-blue-500 block mb-5" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
                    <a class="text-center ml-4 py-3 rounded-lg font-light text-lg w-full text-white bg-red-500 block" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}

            <div class="flex justify-center mt-5">
                <a class="text-blue-500 font-bold text-xl" href="{{room.get_absolute_url}}/edit">Back to Edit</a>
            </div>
        
    </div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block content %}

    <h3>Search!</h3>
    <form action="{% url "rooms:search" %}" method="get">
        {{form.as_p}}
        <!-- <div>
            <label for="city">city</label>
            <input type="text" value="{{city}}" name="city" placeholder="seach by city" id="city">
        
        </div>

        <div>
            <label for="country">country</label>
            <select name="country" id="country">
                {% for country in countries %}
                    <option value="{{country.code}}" {% if country.code is s_country %} selected {% endif %}>{{country.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="room_type">room_type</label>
            <select name="room_type" id="room_type">
                <option value="3" {% if s_room_type is 3 %} selected {% endif %}>Anykind</option>
                {% for room_type in room_types %}
                    <option value="{{room_type.id}}" {% if s_room_type is room_type.pk %} selected {% endif %}>{{room_type.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div>
            <label for="price">price</label>
            <input value="{{price}}" type="number" placeholder="pisaa" name="price" id="price">
        </div>
        
        <div>
            <label for="person">Person</label>
            <input value="{{person}}" type="number" placeholder="person" name="person" id="person">
        </div>

        <div>
            <label for="beds">beds</label>
            <input value="{{beds}}" type="number" placeholder="beds" name="beds" id="beds">
        </div>

        <div>
            <label for="baths">baths</label>
            <input value="{{baths}}" type="number" placeholder="baths" name="baths" id="baths">
        </div>

        <div>
            <label for="instant">Book Instantly ?</label>
            <input type="checkbox" placeholder="instant" name="instant" id="instant"
            {% if instant %}
                checked
            {% endif %}
            >
        </div>

        <div>
            <label for="super_host">By superhost only</label>
            <input type="checkbox" placeholder="super_host" name="super_host" id="instant"
            {% if super_host %}
                checked
            {% endif %}
            >
        </div>


        <div>
            <h3>Amenities</h3>
            <ul>
                {% for a in amenities %}
                    <li>
                        <label for="a_{{a.pk}}">{{a.name}}</label>
                        <input
                            id="a_{{a.pk}}"
                            name="amenities"
                            value="{{a.pk}}"
                            type="checkbox"
                            {% if a.pk|slugify in s_amenities %}
                                checked
                            {% endif %}
                        >
                    </li>
                {% endfor %}
            </ul>
        </div>


        <div>
            <h3>Facilities</h3>
            <ul>
                {% for f in facilities %}
                    <li>
                        <label for="f_{{f.pk}}">{{f.name}}</label>
                        <input
                            id="f_{{f.pk}}"
                            name="facilities"
                            value="{{f.pk}}"
                            type="checkbox"
                            {% if f.pk|slugify in f_facilities %}
                                checked
                            {% endif %}
                        >
                    </li>
                {% endfor %}
            </ul>
        </div> -->

        <button>Search</button>
</form>

<h3>
    Results

    {% for room in rooms %}
        {{room.name}}
    {% endfor %}
</h3>
    

{% endblock content %}