bookings/urls.py
from django.urls import path
from . import views

app_name = "bookings"

urlpatterns = [
    path("create/<int:room>/<int:year>-<int:month>-<int:day>/", views.create, name="create"),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>", views.edit_reservation, name="edit"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("bookings.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views

app_name = "conversations"

urlpatterns = [
    path("go/<int:a_pk>/<int:b_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

bookings/models.py
from django.db import models
from core import models as core_models
from django.utils import timezone
import datetime


class BookedDay(core_models.TimeStampedModel):

    day = models.DateField()
    reservation = models.ForeignKey("Reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"

    def __str__(self):
        return str(self.day)


# Create your models here.
class Reservation(core_models.TimeStampedModel):
    """ reservation model Definition """

    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELLED = "cancelled"

    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELLED, "Cancelled"),
    )

    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING)
    check_in = models.DateField()
    check_out = models.DateField()
    guest = models.ForeignKey("users.User", on_delete=models.CASCADE)
    room = models.ForeignKey("rooms.Room", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.room} - {self.check_in}'

    def in_progress(self):
        now = timezone.now().date() 
        return now >= self.check_in and now <= self.check_out

    in_progress.boolean = True

    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished

    is_finished.boolean = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects.filter(
                day__range=(start, end)
            ).exists()
            if not existing_booked_day:
                super().save(*args, **kwargs)
                for i in range(difference.days + 1):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return
        return super().save(*args, **kwargs)

bookings/views.py
import datetime
from rooms import models as room_models
from . import models
from django.shortcuts import redirect, render, reverse
from django.contrib import messages
from django.views.generic import View
from django.http import Http404
from reviews import forms as review_forms
# Create your views here.


class CreateError(Exception):
    pass


def create(request, room, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        room = room_models.Room.objects.get(pk=room)
        models.BookedDay.objects.get(day=date_obj, reservation__room=room)
        raise CreateError()
    except (room_models.Room.DoesNotExist, CreateError):
        messages.error(request, "Can't Book that")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        reservation = models.Reservation.objects.create(
            guest=request.user,
            room=room,
            check_in=date_obj,
            check_out=date_obj + datetime.timedelta(days=1)
        )
        return redirect(reverse("reservations:detail", kwargs={'pk': reservation.pk}))


class ReservationDetailView(View):

    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if not reservation:
            raise Http404()
        if reservation.guest != self.request.user and reservation.room.owner != self.request.user:
            raise Http404()

        form = review_forms.CreateReviewForm()
        return render(self.request, "bookings/detail.html", {'reservation': reservation, 'form':form})


def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    if not reservation or (reservation.guest != request.user and reservation.room.owner != request.user):
        raise Http404()
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELLED
        models.BookedDay.objects.filter(reservation=reservation).delete()
    reservation.save()
    messages.success(request, "Reservation Update")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))

templates/bookings/detail.html
{% extends "base.html" %}

{% block page_title %}
    booking {{reservation.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    
    <div class="container lg:border-yellow-500 my-10 mx-auto justify-center flex flex-col">

        <div class="border-l border-b border-t bg-cover bg-center h-56 rounded-t-lg" style="background-image: url({{reservation.room.first_photo}});"></div>
        
        <div class="flex flex-col items-start border-l border-b border-t">

            <div class="font-medium py-8 p-x5 w-full ">
                {{reservation.check_in}} - {{reservation.check_out}} <span class=" ml-5 {% if reservation.status == 'pending' %} text-yellow-600 {% elif reservation.status == 'canceled' %} text-red-600 {% else %} text-blue-400 {% endif %}">{{reservation.get_status_display}}</span>
            </div>
    
            <span class="text-2xl border-b p-5 mt-5 w-full">
                {{reservation.room.name}}
            </span>
    
            <div class="flex p-5  border-b w-full">
                <div>
                    <a href="{{room.owner.get_absolute_url}}" class="flex flex-col items-center">
                        <!-- {% include "partials/user_avatar.html" with user=room.owner %} -->
                        {{reservation.room.owner.first_name}}
                    </a>
                </div>
                <div class="ml-5 flex flex-col">
                    <span class="font-medium mb-5">Contact the owner</span>
                    {% if reservation.room.owner.gender == "male" %}
                        <a href="{% url 'conversations:go' reservation.room.owner.pk reservation.guest.pk %}" class="w-full border-2 text-center rounded-sm p-3 bg-blue-500 font-bold">Talk to him</a>
                    {% else %}
                        <a href="{% url 'conversations:go' reservation.room.owner.pk reservation.guest.pk %}" class="w-full border-2 text-center rounded-sm p-3 bg-blue-500 font-bold">Talk to her</a>
                    {% endif %}
                </div>
            </div>
            
            <div class="py-10 px-5 ">
            {% if reservation.status != 'cancelled' %}
                {% if reservation.status == 'confirmed' and reservation.is_finished %}
                    <span class="font-medium text-2xl text-center w-full mb-5">Write Your Review</span>
                    <form action="{% url 'reviews:create' reservation.room.pk %}" method="POST" class="w-1/2 mx-auto">
                        {% csrf_token %}
                        {{form}}
                        <br>
                        <button class="mt-10">Submit Review</button>
                    </form>
                {% else %} 
                    {{reservation.status}}
                        {% if reservation.status == 'pending' %}
                            <a class="w-1/2 border-2 text-center rounded-sm p-3 bg-red-600 text-white font-bold" href="{% url 'reservations:edit' reservation.pk 'cancel' %}">cancel Booking</a>
                            {% if reservation.room.owner == user  %}
                                <a class="w-1/2 border-2 text-center rounded-sm p-3 bg-green-600 text-white font-bold" href="{% url 'reservations:edit' reservation.pk 'confirm' %}">confirm Booking</a>
                            {% endif %}
                        {% endif %}
                {% endif %}
            {% endif %}
        </div>
        </div>
        
    </div>
{% endblock content %}