config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("bookings.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    # path("login/google", views.google_login, name="google-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>/", views.complete_verification, name="complete-verification"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="Profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
]

users/models.py
import uuid
from django.conf import settings
from django.db import models
from django.contrib.auth .models import AbstractUser, UserManager as AbstractUserManager
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.urls import reverse


# from django.contrib.auth import get_user_model
class UserManager(AbstractUserManager):
    pass


# Create your models here.
geneder_choices = (
    ("male", "male"),
    ("female", "female"),
    ("other", "other"),
)

user_language = (
    ("Hindi", "Hindi"),
    ("English", "English"),
)

LOGIN_EMAIL = "email"
LOGIN_GITHUB = "github"
LOGIN_GMAIL = "google"

LOGIN_CHOICES = (
    (LOGIN_EMAIL, "Email"),
    (LOGIN_GITHUB, "github"),
    (LOGIN_GMAIL, "google")
)


class User(AbstractUser):
    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"
    LOGIN_GMAIL = "google"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
        (LOGIN_GMAIL, "Google")
    )
    bio = models.TextField(default="")
    gender = models.CharField(max_length=10, choices=geneder_choices, default="male")
    avatar = models.ImageField(upload_to="avatars", blank=True)
    birthdate = models.DateField(null=True)
    language = models.CharField(max_length=10, choices=user_language, default="Hindi")
    superhost = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)
    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )

    objects = UserManager()

    def get_absolute_url(self):
        return reverse("users:Profile", kwargs={'pk': self.pk})

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "verify BookMyPg Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()
        return

users/forms.py
from django import forms
from . import models
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):

    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    # def clean_email(self):
    #     email = self.cleaned_data.get("email")
    #     try:
    #         models.User.objects.get(username=email)
    #         return email
    #     except models.User.DoesNotExist:
    #         raise forms.ValidationError("User does not exist")

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Wrong Password"))
        except models.User.DoesNotExist:
            self.add_error("email", forms.ValidationError("user does not exist"))


class SignUpForm(forms.ModelForm):

    class Meta:
        model = models.User
        fields = ("first_name", "last_name", "email")

    # first_name = forms.CharField(max_length=80)
    # last_name = forms.CharField(max_length=80)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput, label="confirm password")

    def clean_email(self):
        email = self.cleaned_data.get("email")
        try:
            models.User.objects.get(email=email)
            raise forms.ValidationError("User already exists with that email")
        except models.User.DoesNotExist:
            return email

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")

        if password != password1:
            raise forms.ValidationError("Password confirmation does not match")
        else:
            return password

    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user.username = email
        user.set_password(password)
        user.save()


# class SignUpForm(UserCreationForm):

#     username = forms.EmailField(label="Email")

users/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.urls import reverse_lazy
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
import os
import requests
from users import models
from . import forms, models, mixins
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required

# Create your views here.


class LoginView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        next_arg = self.request.GET.get("next")
        if next_arg is not None:
            return next_arg
        else:
            return reverse("core:home")

    # def get(self, request):
    #     form = forms.LoginForm()
    #     return render(request, "users/login.html", {'form': form})

    # def post(self, request):
    #     form = forms.LoginForm(request.POST)
    #     if form.is_valid():
    #         print(form.cleaned_data)
    #         email = form.cleaned_data.get("email")
    #         password = form.cleaned_data.get("password")
    #         user = authenticate(request, username=email, password=password)
    #         if user is not None:
    #             login(request, user)
    #             return redirect(reverse("core:home"))
    #     return render(request, "users/login.html", {"form": form})


def log_out(request):
    logout(request)
    return redirect(reverse("core:home"))


class SignUpView(FormView):
    template_name = "users/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("core:home")

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=email, password=password)
        if user is not None:
            login(self.request, user)
        user.verify_email()
        return super().form_valid(form)


def complete_verification(request, key):
    try:
        user = models.User.objects.get(email_secret=key)
        user.email_verified = True
        user.email_secret = ""
        user.save()
        # to do: add success message
    except models.User.DoesNotExist:
        # to do : add error message
        pass
    return redirect(reverse("core:home"))


def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "http://127.0.0.1:7000/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


# def google_login(request):
#     client_id = os.environ.get("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY")
#     redirect_uri = "http://127.0.0.1:7000/social-auth/complete/google-oauth2/"
#     return redirect(
#         f"https://google.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
#     )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GithubException("can't get access token")
            else:
                access_token = token_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {access_token}",
                        "Accept": "application/json",
                    },
                )
                # print(profile_request.json())
                profile_json = profile_request.json()
                # print(request.json())
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("login")
                    # email = profile_json.get("login")
                    avatar = profile_json.get("avatar_url", None)
                    bio = profile_json.get("bio")
                    try:
                        # print(f"email is {username}")
                        user = models.User.objects.get(username=username)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            # tryinng to login
                            raise GithubException(
                                f"please login with: {user.login_method}"
                            )
                    except models.User.DoesNotExist:
                        print("sjn")
                        user = models.User.objects.create(
                            email=username,
                            first_name=name,
                            # username=username,
                            bio=bio,
                            avatar=avatar,
                            login_method=models.User.LOGIN_GITHUB,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(
                        request, f"Welcome back {user.first_name}"
                    )
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("can't get your profile")
        else:
            raise GithubException("can't get code")
    except GithubException as e:
        # send error message
        messages.error(request, e)
        return redirect(reverse("users:login"))


class UserProfileView(DetailView):
    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):
    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "email",
        "first_name",
        "last_name",
        "bio",
        "gender",
        "avatar",
        "birthdate",
        "language",
    )

    success_message = "Profile Updated"

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        self.object.username = email
        self.object.save()
        return super().form_valid(form)


class UpdatePasswordView(mixins.EmailLoginOnlyView, mixins.LoggedInOnlyView, SuccessMessageMixin, PasswordChangeView):
    template_name = "users/change_password.html"
    success_message = "Password Updated"

    def get_success_url(self):
        return self.request.user.get_absolute_url()


@login_required
def switch_hosting(request):
    try:
        del request.session['is_hosting']
    except KeyError:
        request.session['is_hosting'] = True
    return redirect(reverse("core:home"))

templates/users/change_password.html
{% extends "base.html" %}

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    
    <div class="container lg:border-yellow-500 lg:w-80 md:w-1/2 xl:w-1/4 my-10 mx-auto justify-center items-center flex flex-col border p-6 border-gray-400">

     

        <form method="POST" action="{% url 'users:password' %}" class="w-full" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <!-- <input type="email" placeholder="Email" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id="">
            <input type="password" placeholder="Password" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id=""> -->
            <button class=" w-full border-2 text-center rounded-sm p-3 bg-yellow-500">Update</button>
        </form>

        

    </div>
{% endblock content %}

templates/users/login.html
{% extends "base.html" %}

{% block page_title %}
    Login 
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    
    <div class="container lg:border-yellow-500 lg:w-80 md:w-1/2 xl:w-1/4 my-10 mx-auto justify-center items-center flex flex-col border p-6 border-gray-400">

        {% include 'partials/social_login.html' %}

     

        <form method="POST" action="{% url "users:login" %}" class="w-full">
            {% csrf_token %}
            {{form}}
            <!-- <input type="email" placeholder="Email" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id="">
            <input type="password" placeholder="Password" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id=""> -->
            <button class=" w-full border-2 text-center rounded-sm p-3 bg-yellow-500">Login</button>
        </form>

        <div class="mt-3">
        <span class="mr-1">Don't have account ? </span>
        <a href="{% url 'users:signup' %}" class="text-blue-600 font-bold">Sign Up</a>
        </div>

    </div>
{% endblock content %}

templates/users/signup.html
{% extends "base.html" %}

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <div class="container lg:border-yellow-500 lg:w-80 md:w-1/2 xl:w-1/4 my-10 mx-auto justify-center items-center flex flex-col border p-6 border-gray-400">

    
    {% include 'partials/social_login.html' %}

    <form action="{% url "users:signup" %}" method="post">
        
        {% csrf_token %}
        {{form.as_p}}
        <button>sign Up</button>
    </form>

    </div>
{% endblock content %}

templates/users/update-profile.html
{% extends "base.html" %}

{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    
    <div class="container lg:border-yellow-500 lg:w-80 md:w-1/2 xl:w-1/4 my-10 mx-auto justify-center items-center flex flex-col border p-6 border-gray-400">

     

        <form method="POST" action="{% url 'users:update' %}" class="w-full" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <!-- <input type="email" placeholder="Email" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id="">
            <input type="password" placeholder="Password" class="w-full border-2 border-gray-500 px-5 focus:outline-none focus:border-yellow-500 text-center rounded-sm p-3 mb-4" name="" id=""> -->
            <button class=" w-full border-2 text-center rounded-sm p-3 bg-yellow-500">Update</button>
        </form>

        {% if object.login_method == "email" %}

        <div class="mt-3">
        <a href="{% url 'users:password' %}" class="text-blue-600 font-bold">Change Password</a>
        </div>

        {% endif %}
    </div>
{% endblock content %}

templates/users/user_detail.html
{% extends "base.html" %}

{% block page_title %}
    {{user_obj.first_name}}'s Profile
{% endblock page_title %}


{% block content %}
    <div class="h-75vh">
            
        <div class="container lg:border-yellow-500 lg:w-80 md:w-1/2 xl:w-1/4 my-10 mx-auto justify-center items-center flex flex-col border p-6 border-gray-400">
            
            <div class="h-20 w-20 bg-gray-700 rounded-full text-white flex justify-center items-center overflow-hidden">

                {% if user_obj.avatar %}
                    <img src="{{user_obj.avatar.url}}" alt="">
                    
                {% else %}
                        <span>{{user_obj.first_name|first}}</span>
                        
                {% endif %}

            </div>
                

            <div class="text-lg mt-3 font-bold">
                {{user_obj.first_name}}
                    {% if user_obj.superhost %}
                            <i class="fas fa-check-circle"></i>
                    {% endif %}
            </div>
            {{user.bio}}
            
            {% if user == user_obj %}

            <a href="{% url 'users:update' %}" class="text-center bg-red-500  rounded-lg py-5 font-semibold mt-4 text-white text-lg w-full"> Edit Profile</a>
            
            {% endif %}

        </div>

        {% if user_obj.rooms.count > 0 %}
        hello
        <div class="container max-auto pb-10 flex flex-col items-center">
            <h3 class="mb-12 text-2xl">{{user_obj.first_name}}'s Room</h3>
            <div class="flex flex-wrap -mx-40 mb-10">
                {% for room in user_obj.rooms.all %}
                    {% include 'partials/room_card.html' %}
                {% endfor %}
            </div>
        </div>
        {% endif %}

    </div>
{% endblock content %}